### ISSUE TITLE
v5.0.0 - SDK Auth configuration missing on activation (I think)

### ISSUE THREAD

**Issue by 89gsc** [auth0/wordpress#857]
### Describe the problem

I have tried to download the new version 5.0.0 and use this to take advantage of the included SDK however, when I try to activate the plugin it will throw a fatal error I can not recover from. 

The error I am seeing is: 

```
[11-Nov-2022 17:25:20 UTC] PHP Fatal error:  Uncaught Auth0\SDK\Exception\ConfigurationException: `domain` must be configured in \web\app\plugins\wp-auth0\vendor\auth0\auth0-php\src\Exception\ConfigurationException.php:62
Stack trace:
#0 \web\app\plugins\wp-auth0\vendor\auth0\auth0-php\src\Configuration\SdkConfiguration.php(1291): Auth0\SDK\Exception\ConfigurationException::requiresDomain()
#1 \web\app\plugins\wp-auth0\vendor\auth0\auth0-php\src\Configuration\SdkConfiguration.php(1239): Auth0\SDK\Configuration\SdkConfiguration->validateStateWebApp()
#2 \web\app\plugins\wp-auth0\vendor\auth0\auth0-php\src\Configuration\SdkConfiguration.php(148): Auth0\SDK\Configuration\SdkConfiguration->validateState()
#3 \web\app\plugins\wp-auth0\src\Plugin.php(304): Auth0\SDK\Configuration\SdkConfiguration->__construct(NULL, 'webapp', NULL, NULL, NULL, 'http://....', NULL, NULL, NULL, true, Array, 'query', 'code', 'RS256', NULL, NULL, 60, NULL, 60, Object(Auth0\WordPress\Http\Client), 3, Object(Auth0\WordPress\Http\MessageFactory\RequestFactory), Object(Auth0\WordPress\Http\MessageFactory\ResponseFactory), Object(Auth0\WordPress\Http\MessageFactory\StreamFactory), true, NULL, 'auth0_session', NULL, NULL, 0, '/', false, NULL)
#4 \web\app\plugins\wp-auth0\src\Plugin.php(65): Auth0\WordPress\Plugin->importConfiguration()
#5 \web\app\plugins\wp-auth0\src\Plugin.php(153): Auth0\WordPress\Plugin->getConfiguration()
#6 \web\app\plugins\wp-auth0\src\Actions\Authentication.php(42): Auth0\WordPress\Plugin->isReady()
#7 \web\wp\wp-includes\class-wp-hook.php(307): Auth0\WordPress\Actions\Authentication->onInit('')
#8 \web\wp\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#9 \web\wp\wp-includes\plugin.php(476): WP_Hook->do_action(Array)
#10 \web\wp\wp-settings.php(598): do_action('init')
#11 \web\wp-config.php(13): require_once('\\www\\...')
#12 \web\wp\wp-load.php(55): require_once('\\www\\...')
#13 \web\wp\wp-blog-header.php(13): require_once('\\www\\...')
#14 \web\index.php(5): require('\\www\\...')
#15 {main}
  thrown in \web\app\plugins\wp-auth0\vendor\auth0\auth0-php\src\Exception\ConfigurationException.php on line 62
```

### What was the expected behavior?

I expect to be able to activate the plugin to add the configuration for the SDK before it tries to just connect up.

### Reproduction

Installed the official WP version of this plugin from the wordpress repo, then used this, connected to auth0 fine, then saw this new version, deleted old plugin, and added version 5.0.0 through composer. 

### Environment

- Version of this library used: 5.0.0
- Which framework are you using, if applicable: Bedrock (installing this in its own plugin folder not using the root composer for this as its not listed in wpackagist yet.) 
- **Other modules/plugins/libraries that might be involved: None that I can think are relevant other than the previous version of the plugin being used before having any impact.
- **Any other relevant information you think would be useful: None but can provide if needed, PHP 8.1 was used to meet the minimum version required, WP 6.0.2

**Comment by evansims** [comment]
Hey @89gsc 👋 Thanks for reporting this! I'll investigate and get back with you.

**Comment by 89gsc** [comment]
I have been asked to test this on a new blank install of wordpress to see if anything with the current stack we have tried to use this with caused the issue. 

I have done this and I get the same error on a non bedrock / standard WP setup. 

![image](https://user-images.githubusercontent.com/1032459/202452126-adda2ffd-6ac0-4d8c-83b9-dceece831844.png)


I am not actually sure the "getting started" instructions for this repo are that useful.

The composer require command is all that's listed as being needed which seems lacking to me, in actually getting this installed I had more hoops to jump through than expected.

- I had to add this repository as a repository available in composer.json or it won't find this. 
- I have to require a something like guzzle to meet the psr/http-client-implementation requirement on a required package of this repo.
- Then that will get you a vendor folder with a folder inside it which is this plugin.
- Then I had to move that folder inside vendor into to wp-content/plugins
- Then I had to run composer install from inside that folder to actually install that plugins requirements.


This doesn't seem normal to me or am I missing something here?

Typically as with the last version of this plugin I tried, I could use a package from https://wpackagist.org/ or via composer which would be pulling from the official wordpress plugin repo which this isn't part of so that's not an option.

**Comment by evansims** [comment]
Thanks for the feedback @89gsc, I'll see what I can do to introduce the onboarding there. My expectation was that you'd run the `composer require` within the wp-content/plugins directory itself, so the repo is forked within that. I should be clearer there.

There may be some issues running V5 with wpackagist.org, I'll look into that.

> I have to require a something like guzzle to meet the psr/http-client-implementation requirement on a required package of this repo.

That should definitely not be happening, as the plugin include's its own network stack now. I think I know the issue there though and it's an easy fix, thanks for letting me know.

**Comment by Johnny99211** [comment]
I'm really angry. I've used the old version and had a lot of problems but at least a working login. Now, I've treid the new one and it's not even loading. I'm getting the same error. And I should pay 23 $ a month? WTF!

**Comment by 89gsc** [comment]
@Johnny99211 please explain how this is relevant to the bug I reported in this issue?

**Comment by evansims** [comment]
👋 Thanks for your patience. [5.0.1](https://github.com/auth0/wordpress/releases/tag/5.0.1) has been released, which resolves this issue.
